# Generated by Django 5.2.5 on 2025-08-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancebatch_attendancerecord_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='batch',
        ),
        migrations.DeleteModel(
            name='AttendanceBatch',
        ),
    ]
