# Generated by Django 5.2.5 on 2025-08-14 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ATTENDANCE_REPORT', 'Attendance Report'), ('PAYROLL_REPORT', 'Payroll Report'), ('EMPLOYEE_REPORT', 'Employee Report'), ('ACKNOWLEDGMENT', 'Acknowledgment')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PeriodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly (7 days)'), ('BIWEEKLY', 'Bi-weekly (15 days)'), ('MONTHLY', 'Monthly (30 days)')], max_length=20)),
                ('report_type', models.CharField(choices=[('EMPLOYEE', 'Employee List'), ('ATTENDANCE', 'Attendance Report'), ('PAYROLL', 'Payroll Report')], max_length=20)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('report_data', models.JSONField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledgment_message', models.TextField(blank=True)),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chief_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.constructionsite')),
                ('site_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('site', 'period_type', 'report_type', 'period_start_date')},
            },
        ),
    ]
