# Generated by Django 5.2.5 on 2025-08-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_sender'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsubmission',
            name='chief_engineer',
        ),
        migrations.RemoveField(
            model_name='payrollsubmission',
            name='site',
        ),
        migrations.RemoveField(
            model_name='payrollsubmission',
            name='site_engineer',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='parent_notification',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('ATTENDANCE', 'Attendance List'), ('PAYROLL', 'Payroll List')], max_length=20)),
                ('submission_date', models.DateField()),
                ('total_records', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_submissions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.constructionsite')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response_type', models.CharField(choices=[('ACKNOWLEDGMENT', 'Acknowledgment'), ('APPROVAL', 'Approval'), ('REJECTION', 'Rejection'), ('COMMENT', 'Comment')], default='ACKNOWLEDGMENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_responses', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='notifications.listsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AttendanceSubmission',
        ),
        migrations.DeleteModel(
            name='PayrollSubmission',
        ),
    ]
