# Generated by Django 5.2.5 on 2025-08-16 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_payrollsubmission_chief_engineer_and_more'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsubmission',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='listsubmission',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='listsubmission',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='listsubmission',
            name='total_records',
        ),
        migrations.RemoveField(
            model_name='listsubmission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='listsubmission',
            name='chief_response',
            field=models.TextField(blank=True, help_text="Chief Engineer's response message"),
        ),
        migrations.AddField(
            model_name='listsubmission',
            name='list_date',
            field=models.DateField(blank=True, help_text='Date for which the list is submitted', null=True),
        ),
        migrations.AddField(
            model_name='listsubmission',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listsubmission',
            name='site_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listsubmission',
            name='chief_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listsubmission',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.constructionsite'),
        ),
        migrations.AlterField(
            model_name='listsubmission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ListResponse',
        ),
    ]
