# Generated by Django 5.2.5 on 2025-08-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_remove_listsubmission_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListSubmission',
        ),
    ]
