# Generated by Django 5.2.5 on 2025-08-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_system_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
