# Generated by Django 5.2.5 on 2025-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rate for this category', max_digits=10),
        ),
    ]
