# Generated by Django 5.2.5 on 2025-08-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_category_daily_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='daily_rate',
        ),
    ]
