# Generated by Django 5.2.5 on 2025-08-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='chief_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='site_engineers',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
