# Generated by Django 5.2.5 on 2025-08-16 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancebatch_attendancerecord_batch'),
        ('payroll', '0001_initial'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_data_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_records',
            field=models.ManyToManyField(blank=True, related_name='payroll_records', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='period_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='periods_worked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='SUBMITTED', max_length=20)),
                ('approval_message', models.TextField(blank=True, null=True)),
                ('chief_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payroll_batches', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches', to='sites.constructionsite')),
                ('site_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_payroll_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='payroll.payrollbatch'),
        ),
    ]
