# Generated by Django 5.2.5 on 2025-08-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_category_daily_rate'),
        ('notifications', '0006_remove_notification_batch_id_and_more'),
        ('payroll', '0002_payrollrecord_attendance_data_used_and_more'),
        ('sites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollbatch',
            options={},
        ),
        migrations.RenameField(
            model_name='payrollbatch',
            old_name='submission_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payrollbatch',
            old_name='approval_date',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='attendance_data_used',
            new_name='is_submitted_for_review',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='approval_message',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='chief_engineer',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='periods_worked',
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='batch_name',
            field=models.CharField(default='Unnamed Batch', max_length=255),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payroll_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='notifications.payrollsubmission'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.constructionsite'),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='site_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.category'),
        ),
    ]
