# Generated by Django 5.2.5 on 2025-08-16 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_category_daily_rate'),
        ('payroll', '0003_alter_payrollbatch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Payroll Record', 'verbose_name_plural': 'Payroll Records'},
        ),
        migrations.RenameField(
            model_name='payrollrecord',
            old_name='submitted_at',
            new_name='payment_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='attendance_records',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='is_submitted_for_review',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='payroll_submission',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount from attendance records', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_period_end',
            field=models.DateField(blank=True, help_text='End date of attendance period', null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='attendance_period_start',
            field=models.DateField(blank=True, help_text='Start date of attendance period', null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='is_payment_confirmed',
            field=models.BooleanField(default=False, help_text='Site Engineer confirms payment was made'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the payroll'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_attendance_days',
            field=models.PositiveIntegerField(default=0, help_text='Total days worked in this period'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.category'),
        ),
        migrations.DeleteModel(
            name='PayrollBatch',
        ),
    ]
