# Generated by Django 5.2.5 on 2025-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payrollrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='attendance_amount',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='attendance_period_end',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='attendance_period_start',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='is_payment_confirmed',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='payment_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='payment_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='total_attendance_days',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='period_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='periods_worked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='NOT_PAID', max_length=20),
        ),
    ]
