# Generated by Django 5.2.5 on 2025-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payrollrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='periods_worked',
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20),
        ),
    ]
